### ISSUE TITLE
수정을 눌렀을 때 오류값이 뜨는데 이유가 뭔지를 모르겠습니다.

### ISSUE THREAD

**Issue by 102wy** [102wy/magazine#1]
안녕하세요 !

https://magazine-c3f45.web.app/
일단 배포한 페이지의 링크입니다!

리덕스를 잘 사용하지 못해서 일어난 문제인것같긴한데
redux - module - magazine 의 updateMagazineFB에서 
const docRef = doc(db, "post", magazine_id);
이 코드를 적기만 해도 오류가 나는데 이유를 알수가 없어서 여쭙니다!
수정을 넘겼을때 값은 콘솔에서 잘 받아와집니다 ㅠㅠ 

오류는 이렇게 발생하고 업데이트 자체도 되지않습니다.ㅠㅠ

index.esm2017.js:1020 Uncaught (in promise) TypeError: u.indexOf is not a function
    at Function.value (index.esm2017.js:1020:19)
    at Wk (index.esm2017.js:16739:19)
    at magazine.js:66:20
    at f (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at o (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)

**Comment by zubetcha** [comment]
원영님 안녕하세요!

말씀해주신 오류는 넘겨준 magazine_id로 firestore에서 데이터를 찾지 못해서 발생하는 것으로 보입니다.

다행히 콘솔을 남겨주셔서 데이터 타입을 확인할 수 있었는데요!

<img width="744" alt="스크린샷 2022-07-23 오후 10 08 10" src="https://user-images.githubusercontent.com/91620721/180606374-a15298df-60dd-4b9b-9e05-859024c1ca6e.png">
<img width="696" alt="스크린샷 2022-07-23 오후 10 04 38" src="https://user-images.githubusercontent.com/91620721/180606550-315e87df-14b0-4de4-8ae9-2c0b78e73b58.png">


확인해보니 magazine_id가 { id: value } 의 형태로 되어 있더라구요. 따라서 doc 메소드의 파라미터로 넘겨줘야 하는 값은 `magazine_id.id`가 되어야 합니다.

<img width="358" alt="스크린샷 2022-07-23 오후 10 15 33" src="https://user-images.githubusercontent.com/91620721/180606672-bee2bd05-a112-4dfa-98f9-44e406576d70.png">

그리고 updateMagazineFB의 두 번째 파라미터로 넘겨주고 있는 magazine_list는 array가 아닌 object 형태이기 때문에 updateDoc 메소드의 파라미터로 넘기고 있는 데이터에서 인덱싱을 의미하는 `[0]`은 모두 제거해주셔야 합니다!

React 심화 주차까지 오시느라 고생 많으셨습니다! ☺️
